### ISSUE TITLE
Crash when hotkey has already been bound

### ISSUE THREAD

**Issue by alexhayes** [fgimian/totalmix-volume-control#3]
As I was trying out the new build I came across an issue which would crash TotalMix Volume Control.

I had forgotten to remove my existing solution to allowing the `Mute` key in Windows to control TotalMix (which I was doing with AutoHotKey and some scripts that then sent OSC messages).

I was seeing the following crash in Event Viewer until I removed the relevant binding in my AutoHotKey script.

```
Application: TotalMixVC.GUI.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (1409): Hot key is already registered.
   at TotalMixVC.GUI.Hotkeys.GlobalHotKeyManager.Register(Hotkey hotkey, Action action) in C:\Users\alex\Documents\workspace\totalmix-volume-control\source\TotalMixVC.GUI\Hotkeys\GlobalHotKeyManager.cs:line 60
   at TotalMixVC.GUI.App.RegisterHotkeys() in C:\Users\alex\Documents\workspace\totalmix-volume-control\source\TotalMixVC.GUI\App.xaml.cs:line 288
   at TotalMixVC.GUI.App.OnStartup(StartupEventArgs e) in C:\Users\alex\Documents\workspace\totalmix-volume-control\source\TotalMixVC.GUI\App.xaml.cs:line 111
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TotalMixVC.GUI.App.Main()
```

**Comment by fgimian** [comment]
Thanks for the report, I'll sort this out in the next release.

**Comment by fgimian** [comment]
This is now fixed and will be released as part of the next update.
